# Generated by Django 4.2.3 on 2023-07-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_project_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="object",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.organizationobject",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="object_name",
            field=models.CharField(
                blank=True, default="object name", max_length=124, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="project_name",
            field=models.CharField(
                blank=True, default="project name", max_length=124, null=True
            ),
        ),
    ]
