# Generated by Django 3.2.20 on 2023-07-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_configuration_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="['%Y-%m-%d %H:%M']"),
        ),
    ]
